/**
 * DO NOT EDIT — GENERATED FILE
 *
 * This file is generated by `scripts/gen-mobile-tailwind.ts` from
 * `@aira/config/design` (packages/config/src/design.ts). Run
 * `pnpm gen:mobile-tw` to regenerate after design tokens change. CI runs
 * `pnpm gen:mobile-tw:check` which fails if this file is out of sync.
 *
 * Hand edits will be overwritten.
 */

/** @type {import('tailwindcss').Config} */
module.exports = {
  "darkMode": "class",
  "content": [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./features/**/*.{js,jsx,ts,tsx}",
    "./lib/**/*.{js,jsx,ts,tsx}"
  ],
  "presets": [
    require("nativewind/preset")
  ],
  "theme": {
    "extend": {
      "colors": {
        "background": "#eaddc1",
        "foreground": "#301d0d",
        "card": "#f2eadd",
        "cardForeground": "#301d0d",
        "popover": "#f5eee0",
        "popoverForeground": "#301d0d",
        "primary": "#496036",
        "primaryForeground": "#f2eadd",
        "secondary": "#f1e7d2",
        "secondaryForeground": "#301d0d",
        "muted": "#e1d6c2",
        "mutedForeground": "#66503f",
        "accent": "#f5eee0",
        "accentForeground": "#301d0d",
        "destructive": "#d40c1a",
        "border": "#785f32",
        "input": "#785f32",
        "ring": "#496036",
        "success": "#496036",
        "successForeground": "#f2eadd",
        "warning": "#c16e2d",
        "warningForeground": "#201308",
        "tier1": "#496036",
        "tier1Foreground": "#f2eadd",
        "tier2": "#c16e2d",
        "tier2Foreground": "#f2eadd",
        "tier3": "#754118",
        "tier3Foreground": "#f2eadd",
        "brandCreamBright": "#f2eadd",
        "brandCreamMuted": "#ecdcc1",
        "brandGold": "#b28b45",
        "info": "#0079ce",
        "infoForeground": "#fafafa",
        "backgroundDark": "#1b0e04",
        "foregroundDark": "#f2eadd",
        "cardDark": "#25170c",
        "cardForegroundDark": "#f2eadd",
        "popoverDark": "#25170c",
        "popoverForegroundDark": "#f2eadd",
        "primaryDark": "#496036",
        "primaryForegroundDark": "#f2eadd",
        "secondaryDark": "#34251a",
        "secondaryForegroundDark": "#f2eadd",
        "mutedDark": "#34251a",
        "mutedForegroundDark": "#ac9c83",
        "accentDark": "#34251a",
        "accentForegroundDark": "#f2eadd",
        "destructiveDark": "#f14e46",
        "borderDark": "#f2eadd",
        "inputDark": "#f2eadd",
        "ringDark": "#6f9352",
        "successDark": "#496036",
        "successForegroundDark": "#f2eadd",
        "warningDark": "#e28d4f",
        "warningForegroundDark": "#1b0e04",
        "tier1Dark": "#496036",
        "tier1ForegroundDark": "#f2eadd",
        "tier2Dark": "#aa5910",
        "tier2ForegroundDark": "#f2eadd",
        "tier3Dark": "#905a33",
        "tier3ForegroundDark": "#f2eadd",
        "brandCreamBrightDark": "#f2eadd",
        "brandCreamMutedDark": "#dfcfb4",
        "brandGoldDark": "#cca45e",
        "infoDark": "#0079ce",
        "infoForegroundDark": "#fafafa"
      },
      "fontSize": {
        "xs": [
          "0.75rem",
          {
            "lineHeight": "1rem"
          }
        ],
        "sm": [
          "0.875rem",
          {
            "lineHeight": "1.25rem"
          }
        ],
        "base": [
          "1rem",
          {
            "lineHeight": "1.5rem"
          }
        ],
        "lg": [
          "1.125rem",
          {
            "lineHeight": "1.75rem"
          }
        ],
        "xl": [
          "1.25rem",
          {
            "lineHeight": "1.75rem"
          }
        ],
        "2xl": [
          "1.5rem",
          {
            "lineHeight": "2rem"
          }
        ],
        "3xl": [
          "1.875rem",
          {
            "lineHeight": "2.25rem"
          }
        ],
        "4xl": [
          "2.25rem",
          {
            "lineHeight": "2.5rem"
          }
        ]
      },
      "borderRadius": {
        "base": "0.875rem",
        "sm": "calc(0.875rem * 0.6)",
        "md": "calc(0.875rem * 0.8)",
        "lg": "0.875rem",
        "xl": "calc(0.875rem * 1.4)",
        "2xl": "calc(0.875rem * 1.8)",
        "full": "9999px"
      },
      "fontFamily": {
        "sans": [
          "Lato-Regular",
          "System"
        ],
        "display": [
          "CormorantGaramond-SemiBold",
          "System"
        ],
        "mono": [
          "Menlo",
          "System"
        ]
      }
    }
  },
  "plugins": []
};
