#!/usr/bin/env tsx
/**
 * gen-mobile-tailwind.ts
 *
 * Generates `apps/mobile/tailwind.config.js` from `@aira/config/design`. This is
 * the SINGLE source of truth — the mobile tailwind config is regenerated, not
 * hand-edited.
 *
 * Modes:
 *   --check   exit 1 if the on-disk file would differ from a fresh generation
 *
 * Usage:
 *   npm run gen:mobile-tw
 *   npm run gen:mobile-tw:check
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { design } from "@aira/config/design";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, "..");
const OUT_PATH = resolve(REPO_ROOT, "apps/mobile/tailwind.config.js");

const HEADER = `/**
 * DO NOT EDIT — GENERATED FILE
 *
 * This file is generated by \`scripts/gen-mobile-tailwind.ts\` from
 * \`@aira/config/design\` (packages/config/src/design.ts). Run
 * \`pnpm gen:mobile-tw\` to regenerate after design tokens change. CI runs
 * \`pnpm gen:mobile-tw:check\` which fails if this file is out of sync.
 *
 * Hand edits will be overwritten.
 */
`;

/**
 * oklch → sRGB hex conversion (Björn Ottosson's OKLab spec).
 *
 * React Native's color parser only accepts rgb/rgba/hex/named values. NativeWind
 * v4 claims runtime CSS color support but in practice oklch() strings silently
 * fall back to default (white/transparent) inside RN — which is what made every
 * `bg-background`, `bg-card`, etc. render as white in Expo Go (2026-06-29).
 *
 * Web continues to consume the oklch source directly via globals.css; only the
 * mobile generated config gets the hex equivalents emitted by this fn. The
 * design tokens stay oklch — single source of truth, lossy conversion happens
 * at the boundary.
 *
 * Formula: https://bottosson.github.io/posts/oklab/
 */
function oklchToHex(input: string): string {
  const m = input
    .replace(/\s+/g, " ")
    .match(/^oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)(?:\s*\/\s*([\d.%]+))?\s*\)$/);
  if (!m) {
    // Pass through if already hex / named / unparseable — the caller's
    // problem to fix.
    return input;
  }
  const L = Number(m[1]);
  const C = Number(m[2]);
  const H = Number(m[3]);

  // OKLch → OKLab
  const a = C * Math.cos((H * Math.PI) / 180);
  const b = C * Math.sin((H * Math.PI) / 180);

  // OKLab → linear LMS
  const l_ = L + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = L - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = L - 0.0894841775 * a - 1.291485548 * b;

  const ll = l_ * l_ * l_;
  const mm = m_ * m_ * m_;
  const ss = s_ * s_ * s_;

  // Linear LMS → linear sRGB
  let r = +4.0767416621 * ll - 3.3077115913 * mm + 0.2309699292 * ss;
  let g = -1.2684380046 * ll + 2.6097574011 * mm - 0.3413193965 * ss;
  let bl = -0.0041960863 * ll - 0.7034186147 * mm + 1.707614701 * ss;

  // Linear sRGB → sRGB (gamma)
  const gamma = (x: number): number =>
    x <= 0.0031308 ? 12.92 * x : 1.055 * Math.pow(x, 1 / 2.4) - 0.055;
  r = gamma(r);
  g = gamma(g);
  bl = gamma(bl);

  const toByte = (n: number): number =>
    Math.round(Math.max(0, Math.min(1, n)) * 255);
  const hex = (n: number): string => toByte(n).toString(16).padStart(2, "0");
  return `#${hex(r)}${hex(g)}${hex(bl)}`;
}

function colorsToTailwind(): Record<string, string | Record<string, string>> {
  // We use the LIGHT palette as the default Tailwind color map. Dark tokens
  // get a `*Dark` suffix so consumers can opt-in via explicit class names.
  //
  // CRITICAL: every value is emitted as sRGB hex — RN's color parser does
  // not handle oklch() and NativeWind v4 doesn't convert it for us. Keeping
  // the source as oklch in design.ts (matches web globals.css) and
  // converting at generation time keeps both surfaces in sync without a
  // shared color lib.
  const light = design.colors.light;
  const dark = design.colors.dark;
  const out: Record<string, string | Record<string, string>> = {};
  for (const key of Object.keys(light) as Array<keyof typeof light>) {
    out[String(key)] = oklchToHex(light[key]);
  }
  for (const key of Object.keys(dark) as Array<keyof typeof dark>) {
    out[`${String(key)}Dark`] = oklchToHex(dark[key]);
  }
  return out;
}

function fontSize(): Record<string, [string, { lineHeight: string }]> {
  const out: Record<string, [string, { lineHeight: string }]> = {};
  for (const [name, val] of Object.entries(design.type)) {
    out[name] = [val.size, { lineHeight: val.line }];
  }
  return out;
}

function build(): string {
  const colors = colorsToTailwind();
  const sizes = fontSize();
  const radius = design.radius;
  const config = {
    // NativeWind v4's web runtime needs `class` mode so it can apply
    // dark-mode classes on <html>. With the default `media`, react-native-
    // css-interop throws "Cannot manually set color scheme" the moment
    // anything observes the OS preference change.
    darkMode: "class",
    content: [
      "./app/**/*.{js,jsx,ts,tsx}",
      "./components/**/*.{js,jsx,ts,tsx}",
      "./features/**/*.{js,jsx,ts,tsx}",
      "./lib/**/*.{js,jsx,ts,tsx}",
    ],
    presets: [require_nativewind_preset_placeholder()],
    theme: {
      extend: {
        colors,
        fontSize: sizes,
        borderRadius: radius,
        fontFamily: {
          sans: ["Lato-Regular", "System"],
          display: ["CormorantGaramond-SemiBold", "System"],
          mono: ["Menlo", "System"],
        },
      },
    },
    plugins: [],
  };
  // Serialize to JS source. We embed the require() literal by replacing the
  // sentinel string back to a `require(...)` call after JSON stringify.
  const json = JSON.stringify(config, null, 2);
  const withRequire = json.replace(
    '"__NATIVEWIND_PRESET__"',
    'require("nativewind/preset")'
  );
  return `${HEADER}\n/** @type {import('tailwindcss').Config} */\nmodule.exports = ${withRequire};\n`;
}

function require_nativewind_preset_placeholder(): string {
  return "__NATIVEWIND_PRESET__";
}

function main() {
  const check = process.argv.includes("--check");
  const generated = build();
  if (check) {
    if (!existsSync(OUT_PATH)) {
      console.error(
        `[gen-mobile-tw] ${OUT_PATH} does not exist. Run \`npm run gen:mobile-tw\`.`
      );
      process.exit(1);
    }
    const current = readFileSync(OUT_PATH, "utf8");
    if (current !== generated) {
      console.error(
        "[gen-mobile-tw] apps/mobile/tailwind.config.js is OUT OF SYNC with @aira/config/design."
      );
      console.error("Run `npm run gen:mobile-tw` and commit the result.");
      process.exit(1);
    }
    console.log("[gen-mobile-tw] In sync.");
    return;
  }
  writeFileSync(OUT_PATH, generated, "utf8");
  console.log(`[gen-mobile-tw] Wrote ${OUT_PATH}`);
}

main();
