#!/usr/bin/env tsx
/**
 * gen-mobile-tailwind.ts
 *
 * Generates `apps/mobile/tailwind.config.js` from `@mlabs/config/design`. This is
 * the SINGLE source of truth — the mobile tailwind config is regenerated, not
 * hand-edited.
 *
 * Modes:
 *   --check   exit 1 if the on-disk file would differ from a fresh generation
 *
 * Usage:
 *   npm run gen:mobile-tw
 *   npm run gen:mobile-tw:check
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { design } from "@mlabs/config/design";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, "..");
const OUT_PATH = resolve(REPO_ROOT, "apps/mobile/tailwind.config.js");

const HEADER = `/**
 * DO NOT EDIT — GENERATED FILE
 *
 * This file is generated by \`scripts/gen-mobile-tailwind.ts\` from
 * \`@mlabs/config/design\` (packages/config/src/design.ts). Run
 * \`pnpm gen:mobile-tw\` to regenerate after design tokens change. CI runs
 * \`pnpm gen:mobile-tw:check\` which fails if this file is out of sync.
 *
 * Hand edits will be overwritten.
 */
`;

function colorsToTailwind(): Record<string, string | Record<string, string>> {
  // We use the LIGHT palette as the default Tailwind color map and rely on
  // NativeWind's dark: variants which read from the same `darkVars` pattern.
  // For React Native NativeWind v4 the color values must be valid CSS
  // color strings; oklch() is supported in NativeWind v4.
  const light = design.colors.light;
  const dark = design.colors.dark;
  const out: Record<string, string | Record<string, string>> = {};
  // Emit each token as { DEFAULT: light, dark: dark } so consumers can write
  // text-foreground (light) and dark:text-foreground-dark.
  for (const key of Object.keys(light) as Array<keyof typeof light>) {
    out[String(key)] = light[key];
  }
  for (const key of Object.keys(dark) as Array<keyof typeof dark>) {
    out[`${String(key)}Dark`] = dark[key];
  }
  return out;
}

function fontSize(): Record<string, [string, { lineHeight: string }]> {
  const out: Record<string, [string, { lineHeight: string }]> = {};
  for (const [name, val] of Object.entries(design.type)) {
    out[name] = [val.size, { lineHeight: val.line }];
  }
  return out;
}

function build(): string {
  const colors = colorsToTailwind();
  const sizes = fontSize();
  const radius = design.radius;
  const config = {
    // NativeWind v4's web runtime needs `class` mode so it can apply
    // dark-mode classes on <html>. With the default `media`, react-native-
    // css-interop throws "Cannot manually set color scheme" the moment
    // anything observes the OS preference change.
    darkMode: "class",
    content: [
      "./app/**/*.{js,jsx,ts,tsx}",
      "./components/**/*.{js,jsx,ts,tsx}",
      "./features/**/*.{js,jsx,ts,tsx}",
      "./lib/**/*.{js,jsx,ts,tsx}",
    ],
    presets: [require_nativewind_preset_placeholder()],
    theme: {
      extend: {
        colors,
        fontSize: sizes,
        borderRadius: radius,
        fontFamily: {
          sans: ["Geist", "System"],
          display: ["Geist", "System"],
          mono: ["GeistMono", "Menlo"],
        },
      },
    },
    plugins: [],
  };
  // Serialize to JS source. We embed the require() literal by replacing the
  // sentinel string back to a `require(...)` call after JSON stringify.
  const json = JSON.stringify(config, null, 2);
  const withRequire = json.replace(
    '"__NATIVEWIND_PRESET__"',
    'require("nativewind/preset")'
  );
  return `${HEADER}\n/** @type {import('tailwindcss').Config} */\nmodule.exports = ${withRequire};\n`;
}

function require_nativewind_preset_placeholder(): string {
  return "__NATIVEWIND_PRESET__";
}

function main() {
  const check = process.argv.includes("--check");
  const generated = build();
  if (check) {
    if (!existsSync(OUT_PATH)) {
      console.error(
        `[gen-mobile-tw] ${OUT_PATH} does not exist. Run \`npm run gen:mobile-tw\`.`
      );
      process.exit(1);
    }
    const current = readFileSync(OUT_PATH, "utf8");
    if (current !== generated) {
      console.error(
        "[gen-mobile-tw] apps/mobile/tailwind.config.js is OUT OF SYNC with @mlabs/config/design."
      );
      console.error("Run `npm run gen:mobile-tw` and commit the result.");
      process.exit(1);
    }
    console.log("[gen-mobile-tw] In sync.");
    return;
  }
  writeFileSync(OUT_PATH, generated, "utf8");
  console.log(`[gen-mobile-tw] Wrote ${OUT_PATH}`);
}

main();
