import * as React from "react";
import { Text, View } from "react-native";
import {
  TIER_LABELS,
  type BusinessTier,
} from "@aira/validators";

interface TierPillProps {
  tier: BusinessTier;
}

/**
 * Small rounded badge marking a paid-sponsorship business. Visual port
 * of web's TierPill (apps/web/src/features/listings/components/business-card.tsx:147).
 *
 * Returns null for tier3 (Regular / unpaid) — only tier1 + tier2 show
 * the badge on public surfaces. Label is sourced from the shared
 * TIER_LABELS map in @aira/validators so the badge text matches web,
 * tier-section, admin tables, and the plan picker exactly (no drift).
 *
 * Colors source from the design-token classes generated by
 * scripts/gen-mobile-tailwind.ts — `bg-tier1` / `text-tier1Foreground`
 * (olive on cream) and `bg-tier2` / `text-tier2Foreground` (burnt
 * orange on cream). Contrast pairs are checked by the lefthook
 * `check-contrast` hook on every commit.
 *
 * Sizing matches web's `px-1.5 py-px text-[0.55rem] font-bold tracking-wide`
 * — translates on RN to 6pt horizontal padding, 1pt vertical, 9pt font
 * weight 700 with letterSpacing 0.5.
 */
export function TierPill({ tier }: TierPillProps) {
  if (tier === "tier3") return null;

  const className =
    tier === "tier1"
      ? "rounded-full bg-tier1 px-1.5"
      : "rounded-full bg-tier2 px-1.5";

  const textClassName =
    tier === "tier1"
      ? "text-tier1Foreground"
      : "text-tier2Foreground";

  return (
    <View
      className={className}
      style={{ paddingVertical: 1 }}
      accessibilityLabel={`${TIER_LABELS[tier]} listing`}
    >
      <Text
        className={textClassName}
        style={{ fontSize: 9, fontWeight: "700", letterSpacing: 0.5 }}
      >
        {TIER_LABELS[tier]}
      </Text>
    </View>
  );
}
